Added intergration for WebsocketServer with HttpListner
nanoframework/System.Net.WebSockets pull request #20
Opened 2022-01-12 19:33 UTC by Feiko

## Description
WebsocketServer can now run in stand-alone mode and be integrated with HttpListner Server
You can now directly add a new websocketClient by handing the HttpListnerContext over to the WebsocketServer. For this one has to start the webserver setting the WebSocketServerOptions.IsStandAlone to false. Preventing the websocketserver from listening to incoming TCP websocket request.

```
s_wsServer = new WebSocketServer(new WebSocketServerOptions()
            {
                MaxClients = 10,
                IsStandAlone = false;
            });

```

A websocket can be added by calling the method:
`bool AddWebSocket(HttpListenerContext context)`

- The library now depends System.Net.Http.
- No breaking changes to the API
- Stand-Alone websocket server now uses the HttpListner for handling incoming requests

## Motivation and Context
Running a website with websockets does no longer require you to host the websocket and the website on another. Saving resources and less code. 

## How Has This Been Tested?
Ran multiple tests attaching browsers and stand-alone websocket clients

## Screenshots

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-01-12 22:51 UTC, josesimoes requested changes

2022-01-12 22:51 UTC, josesimoes commented on WebSockets.Client/packages.config
> +  <package id="nanoFramework.System.Net.Http" version="1.4.0-preview.3" targetFramework="netnanoframework10" />
```suggestion
  <package id="nanoFramework.System.Net.Http" version="1.4.0-preview.4" targetFramework="netnanoframework10" />
```

2022-01-12 22:51 UTC, josesimoes commented on WebSockets/WebSocketServer/WebSocketServerOptions.cs
> +        /// Determents if the websocket runs as a independent websocket server with it's own HttpListner.
```suggestion
        /// Determines if the websocket runs as a independent websocket server with it's own HttpListner.
```

2022-01-12 22:51 UTC, josesimoes commented on WebsocketHttpContextTester/WebsocketHttpContextTester.nfproj
> +      <HintPath>..\packages\nanoFramework.System.Net.1.8.0-preview.5\lib\System.Net.dll</HintPath>
```suggestion
      <HintPath>..\packages\nanoFramework.System.Net.1.8.0-preview.9\lib\System.Net.dll</HintPath>
```

2022-01-12 22:51 UTC, josesimoes commented on WebsocketHttpContextTester/packages.config
> +  <package id="nanoFramework.System.Net" version="1.8.0-preview.5" targetFramework="netnanoframework10" />
```suggestion
  <package id="nanoFramework.System.Net" version="1.8.0-preview.9" targetFramework="netnanoframework10" />
```

2022-01-12 22:51 UTC, josesimoes commented on Websockets.Client/System.Net.WebSockets.Client.nfproj.bak
> +<?xml version="1.0" encoding="utf-8"?>
remove this bak file please

2022-01-12 22:51 UTC, josesimoes commented on Websockets.Client/packages.config.bak
> +﻿<?xml version="1.0" encoding="utf-8"?>
another, and others after this

2022-01-12 22:51 UTC, josesimoes commented on WebsocketHttpContextTester/Program.cs
> +            Thread.Sleep(-1);
better use this instead of "magic" numbers
```suggestion
            Thread.Sleep(Timeout.Infinite);
```

2022-01-12 22:51 UTC, josesimoes commented on WebsocketHttpContextTester/Program.cs
> +
OK to clear all line after this

2022-01-12 22:51 UTC, josesimoes commented on WebsocketHttpContextTester/Program.cs
> +
no need for all these empty lines

2022-01-12 22:52 UTC, josesimoes commented
My question from the previous PR is still valid: do we need HTTP for the client only library?

2022-01-13 10:56 UTC, Feiko commented on WebsocketHttpContextTester/Program.cs
> +
WEbsocketHttpContextTester was a remnant that should not have been checked in. Is deleted now.

2022-01-13 11:23 UTC, Feiko commented
> My question from the previous PR is still valid: do we need HTTP for the client only library?

You're right, HTTP Client does not need the HTTP library, this has been removed from the Websocket Client Package

2022-01-13 11:24 UTC, josesimoes approved these changes
LGTM! And it's building just fine. 💯 🥳

2022-01-13 11:24 UTC, merged